services:
    _defaults:
        autowire: true
        autoconfigure: true
    _instanceof:
        Symfony\Component\Console\Command\Command:
            tags: ['command']

    Atoolo\Search\Console\:
        resource: '../src/Console'

    atoolo.search.indexer.console.progressBar:
      class:  'Atoolo\Search\Console\Command\Io\IndexerProgressBar'

    Atoolo\Search\Console\Command\Indexer:
      arguments:
        - '@atoolo.resource.resourceChannelFactory'
        - '@atoolo.search.indexer.console.progressBar'
        - '@atoolo.search.indexer.indexerCollection'

    Atoolo\Search\Console\Command\Search:
      arguments:
        - '@atoolo.resource.resourceChannelFactory'
        - '@atoolo.search.search'

    Atoolo\Search\Console\Command\Suggest:
      arguments:
        - '@atoolo.resource.resourceChannelFactory'
        - '@atoolo.search.suggest'

    Atoolo\Search\Console\Command\MoreLikeThis:
      arguments:
        - '@atoolo.resource.resourceChannelFactory'
        - '@atoolo.search.moreLikeThis'

    Atoolo\Search\Console\Command\DumpIndexDocument:
      arguments:
        - '@atoolo.resource.resourceChannelFactory'
        - '@atoolo.search.indexer.indexDocumentDumper'

    Atoolo\Search\Console\Application:
        public: true
        arguments:
            - !tagged command